services:
  db:
    image: postgres:16
    container_name: automotores_db
    environment:
      POSTGRES_DB: automotores_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d automotores_db']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: automotores_api
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: automotores_db
      PORT: 3000
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
